# Copyright (c) LieberLieber GmbH & Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Verify LTA ConsistencyCheck

on:
 push:
  branches:
      - main

env:
  ModelName: LemonTree.DevOps.Demo.qeax
  # cached executable paths used by tool setup steps
  LTA_DIR: ${{ github.workspace }}\_toolcache\LTA

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0      
     
      # download Lemontree.Automation on a runner and setup the license
      # when using private runners LemonTree.Automation can be installed manually and this step can be skipped
      # Custom action to setup LemonTree Automation that supports caching
      - name: Setup LemonTree Automation
        uses: ./.github/actions/setup-lta
        id: GetLTA
        with:
          lta-url: https://www.lieberlieber.com/lemontree/automation/latest
          lta-dir: ${{ env.LTA_DIR }}
          license: ${{secrets.LTALICENSE}}
      - name: ConsistencyCheck
        run: |
          &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}
 
     
    
